### ISSUE TITLE
Deactivate play-wide user privilege escalation (become: true)

### ISSUE THREAD

**Issue by PedrosWits** [PedrosWits/maestro#9]
User privilege escalation for group playbooks, should be allowed on a per role basis instead of for the whole playbook.

**Comment by PedrosWits** [comment]
**Current behavior:**

```
- hosts: anpr-server
   gather_facts: yes
   remote_user: jsnow
   become: yes

   tasks:

     - name: Execute role 'webofmars.dummy'
       include_role:
         name: webofmars.dummy

     - name: Execute role 'anpr_mssql_server'
       include_role:
         name: anpr_mssql_server
```

**Desired behavior:**

```
- hosts: anpr-server
   gather_facts: yes
   remote_user: jsnow

   tasks:

     - name: Execute role 'webofmars.dummy'
       include_role:
         name: webofmars.dummy
       become: yes

     - name: Execute role 'anpr_mssql_server'
       include_role:
         name: anpr_mssql_server
       become: no
```
